# PERSONALIZATION
# Site variables
name: Computer Science Graduate Student Association at University of Colorado Boulder
alternate_logo: assets/img/gpdc_logo_bw.png
logo: assets/img/logo.png

front_photo: 
  photo: assets/img/team-group.jpeg
  alt:  CSGSA leadership committee of AY 25-26
  caption: Current members of the CSGSA and CSGPDC.

original_repo: https://github.com/cucsgsa/events-landing
description: CS Graduate Student Association at CU website
# ga: UA-109088240-1
domain: cucsgsa.github.io/landing/

#youtube plugin for CS-GPDC's youtube page
#plugins: [jekyll-youtube]

# Style variables
background_color: "#FAFAFA"
footer_text_color: "#666666"
events_bg_img: assets/img/people.jpg
future: false

# CU THEME
accent_color: "#344882"
accent_color2: "#000000"
events_overlay_color: "#000"
# END CU THEME

# Author variables
author: Computer Science Graduate Student Association at University of Colorado Boulder
email: csgsa@colorado.edu

# Social media + community variables
# fb: hackcu
slack-signup: https://boulder-cs-grads.slack.com
github-org: CUCSGSA

# TIMEZONE
# Needs to be string from: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: America/Denver
# Based on: http://erics-notes.blogspot.com/2013/05/fixing-ics-time-zone.html
ical_timezone: |-
  BEGIN:DAYLIGHT
  TZOFFSETFROM:-0700
  TZOFFSETTO:-0600
  TZNAME:MDT
  DTSTART:19700308T020000
  RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=2SU
  END:DAYLIGHT
  BEGIN:STANDARD
  TZOFFSETFROM:-0600
  TZOFFSETTO:-0700
  TZNAME:MST
  DTSTART:19701101T020000
  RRULE:FREQ=YEARLY;BYMONTH=11;BYDAY=1SU
  END:STANDARD
 
# Internal configuration
sass:
    sass_dir: assets/_sass
    style: compressed

collections:
  newsletters:
    output: true
    permalink: /newsletters/:year/:month/:day/
